//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRProject_GUI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class UISettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UISettings defaultInstance = ((UISettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UISettings())));
        
        public static UISettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dictionary-WithStemming")]
        public string DictionaryWithStemming {
            get {
                return ((string)(this["DictionaryWithStemming"]));
            }
            set {
                this["DictionaryWithStemming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dictionary-WithoutStemming")]
        public string DictionaryWithoutStemming {
            get {
                return ((string)(this["DictionaryWithoutStemming"]));
            }
            set {
                this["DictionaryWithoutStemming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Posting-WithStemming\r\n")]
        public string PostingWithStemming {
            get {
                return ((string)(this["PostingWithStemming"]));
            }
            set {
                this["PostingWithStemming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Posting-WithoutStemming")]
        public string PostingWithoutStemming {
            get {
                return ((string)(this["PostingWithoutStemming"]));
            }
            set {
                this["PostingWithoutStemming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Documents-WithStemming")]
        public string DocumentsWithStemming {
            get {
                return ((string)(this["DocumentsWithStemming"]));
            }
            set {
                this["DocumentsWithStemming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Documents-WithoutStemming")]
        public string DocumentsWithoutStemming {
            get {
                return ((string)(this["DocumentsWithoutStemming"]));
            }
            set {
                this["DocumentsWithoutStemming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OLLADI_RESULT_")]
        public string SaveResult {
            get {
                return ((string)(this["SaveResult"]));
            }
            set {
                this["SaveResult"] = value;
            }
        }
    }
}
